### ISSUE TITLE
replace yaml.load with yaml.safe_load

### ISSUE THREAD

**Issue by sreerajkksd** [knorby/facterpy#11]
yaml.load now issue the following warning:

```
  In [1]: import facter
  In [2]: facts_helper = facter.Facter()
  In [3]: facts = facts_helper.all
  /usr/local/python/python-3.7/latest/lib64/python3.7/site-packages/facter/__init__.py:81: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
    parsed_results = yaml.load(results)
````

It is a single line change to fix. 

I don't mind raising a PR, but @knorby Can you apply it and release it as a new version ?

**Comment by knorby** [comment]
@sreerajkksd send a PR, and I can cut a new release

**Comment by sreerajkksd** [comment]
Here you go: https://github.com/knorby/facterpy/pull/12

**Comment by sreerajkksd** [comment]
@knorby would you approve and merge this ?

**Comment by sreerajkksd** [comment]
@knorby Would you please cut a new release ? (and deploy a version in pypi)

**Comment by sreerajkksd** [comment]
@knorby Can you cut a new release ?
